name: movie_app
description: Mobile Programming Project - Flutter

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  build_runner: ^1.10.0
  flutter_mobx: ^2.0.0-nullsafety.3
  mobx_codegen: ^2.0.1+3
  mobx: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_database: ^8.1.0
  firebase_core: ^1.10.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
